### ISSUE TITLE
fail to add br1 with ovs-vsctl “Bridge does not contain a column whose name matches "p4"”

### ISSUE THREAD

**Issue by HAIYAA** [osinstom/P4-OvS#10]
Hello, sorry to bother you, but I had a problem not finding a solution. I've had this problem after following demo.
```
ovs-vsctl add-br br1 -- set bridge br0 datapath_type=ubpf p4=true
ovs-vsctl: Bridge does not contain a column whose name matches "p4"
```
but i've already install the p4c, PI and p4-ovs,  is it because there is any configuration I did't do?

**Comment by gabrielgonzalezcampos** [comment]
Hello, sorry for commenting here, but I'm trying to run p4-ovs demo and I'm not able to do it, when I run: `ovs-vsctl add-br br1 -- set bridge br0 datapath_type=ubpf p4=true` it stays waiting for something forever. 
Can you explain how you intalled it?
Hundred thanks

**Comment by serendip1t** [comment]
I also meet the problem that "ovs-vsctl: Bridge does not contain a column whose name matches "p4" '
how to resolve it?
thanks too much

**Comment by HAIYAA** [comment]
> I also meet the problem that "ovs-vsctl: Bridge does not contain a column whose name matches "p4" ' how to resolve it? thanks too much

actually, I haven't solved this problem, I doubt that this project has some issues that not be fixed. btw, I noticed that 3 years ago this project stopped updating, so maybe you can find some other way to achieve the p4 in OVS. From what I know is that some people program the P4-OVS using VPP.
